---
title: Benjamin Howes
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/:title/"
  uploads:
    title: Uploads
    output: true

defaults:
  - scope:
      path: ''
      type: projects
    values:
      layout: post
      tags: false
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext
  - scope:
      path: '_posts'
    values:
      permalink: /blog/:slug


markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-sitemap

show_downloads: false

sass:
  sass_dir: _sass
  style: compressed

permalink: /:title
paginate: 9
paginate_path: "/blog/page/:num"

exclude:
  - docker-compose.yml
  - vendor
