---
title: Benjamin Howes
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/:title/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: projects
  values:
    layout: post
    tags: false
email: ben@ben-howes.co.uk
description: Software Engineer & Entrepreneur guy
baseurl: ''
url: https://ben-howes.co.uk
author: Benjamin Howes
twitter_username: ben_howes
github_username: benhowes
linkedin_profile: https://www.linkedin.com/in/benjaminhowes/
footer: "&copy; Ben Howes. Theme based on [Github pages hacker](https://github.com/pages-themes/hacker).\n"
markdown: kramdown
theme: jekyll-theme-hacker
plugins:
- jekyll-feed
show_downloads: false
