version: '3'
services:
  jekyll:
      image: jekyll/jekyll:3.8
      environment:
        - JEKYLL_ENV=development
      command: jekyll serve --force_polling --drafts --incremental -l
      ports:
          - 4000:4000
          - 35729:35729
      volumes:
          - .:/srv/jekyll
          - ./vendor/bundle:/usr/local/bundle
