email: ben@ben-howes.co.uk
baseurl: ''

url: https://ben-howes.co.uk
description: Software Engineer & Entrepreneur
twitter_username: ben_howes
github_username: benhowes
linkedin_profile: https://www.linkedin.com/in/benjaminhowes/

footer: "&copy; Ben Howes"

title: Benjamin Howes
hero:
  hero__title: Hi, I’m Ben. I am the founder of [Capable Koala](https://capablekoala.co), and freelance regulatory consultant at [Hardian Health](https://www.hardianhealth.com/).
  hero__description: >
    I post here about what I'm working on and learning.

    To contact me; reach out [on linkedin](https://www.linkedin.com/in/benjaminhowes/) or email "ben@" this domain.

portfolio__title: Projects


#-------------------------------
# Menu Settings
menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'Blog'
      url: '/blog/'
    - title: 'Book shelf'
      url: '/books/'


#-------------------------------
# Footer Settings
social:
- {icon: "ion-globe-outline", color: "#55acee", label: Bluesky, link: "https://bsky.app/profile/benhowes.bsky.social"}
- {icon: "ion-logo-github", color: "#24292e", label: GitHub, link: "https://github.com/benhowes"}
- {icon: "ion-logo-linkedin", color: "#0077B5", label: Linkedin, link: "https://www.linkedin.com/in/benjaminhowes/"}
